image: Visual Studio 2017

install:
  - choco install gitversion.portable -pre -y

assembly_info:
  patch: false

before_build:
  - cmd: dotnet --version
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build_script:
  - cmd: msbuild /t:Pack /p:Verion="%GitVersion_NuGetVersion%" ./src/MassTransit.EventStoreIntegration/MassTransit.EventStoreIntegration.csproj

test_script:
  - cmd: dotnet test ./src/MassTransit.EventStoreIntegration.Tests/MassTransit.EventStoreIntegration.Tests.csproj