-
  branches:
    only:
      - master

  image: Visual Studio 2017

  install:
    - choco install gitversion.portable -pre -y

  assembly_info:
    patch: false

  artifacts:
    path: 'src\MassTransit.EventStoreIntegration\bin\Release\*.nupkg'

  configuration: Release

  before_build:
    - cmd: dotnet --version
    - ps: gitversion /l console /output buildserver /updateAssemblyInfo
    - cmd: dotnet restore ./src/MassTransit.EventStoreIntegration.sln

  build_script:
    - cmd: msbuild /t:Pack /p:Configuration=Release /p:Verion="%GitVersion_NuGetVersion%" ./src/MassTransit.EventStoreIntegration/MassTransit.EventStoreIntegration.csproj

  test_script:
    - cmd: dotnet test ./src/MassTransit.EventStoreIntegration.Tests/MassTransit.EventStoreIntegration.Tests.csproj
-
  branches:
    only:
      - develop

  image: Visual Studio 2017

  install:
    - choco install gitversion.portable -pre -y

  assembly_info:
    patch: false

  artifacts:
    path: 'src\MassTransit.EventStoreIntegration\bin\Debug\*.nupkg'

  configuration: Debug

  build_script:
    - dotnet --version
    - gitversion /l console /output buildserver
    - echo %GitVersion_NuGetVersion%
    - dotnet restore ./src/MassTransit.EventStoreIntegration.sln
    - msbuild /t:Pack /p:Configuration=Debug /p:Verion=%GitVersion_NuGetVersion% ./src/MassTransit.EventStoreIntegration/MassTransit.EventStoreIntegration.csproj

  test_script:
    - cmd: dotnet test ./src/MassTransit.EventStoreIntegration.Tests/MassTransit.EventStoreIntegration.Tests.csproj
