version: '3.5'

services:

  eventstore:
    container_name: mt-eventstore
    image: eventstore/eventstore
    ports:
      - '2113:2113'
      - '1113:1113'
    environment:
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_RUN_PROJECTIONS=all
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true

networks:
  default:
    name: mt-es-test
