name: Build and deploy

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Run tests netcoreapp3.1
        run: |
          docker-compose -d up
          dotnet test -c Release -f netcoreapp3.1
          docker-compose down
    
  nuget:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
    - uses: actions/checkout@v1

    - name: Create NuGet package
      run: dotnet pack -c Release -o nuget -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg

    - name: Push NuGet package
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      
  