name: Build and test PRs

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
          
      - name: Run tests netcoreapp3.1
        run: |
          docker-compose up
          dotnet test -c Release -f netcoreapp3.1
          docker-compose down
